# Essential Thai OCR Config
number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'กขคงจชซญณดตถทธนบปผฝพฟมยรลวศสหอะัาำิีึืุูเแโใไ็่้'
experiment_name: 'thai_auto'
train_data: 'all_data'
valid_data: 'all_data/thai_val'
manualSeed: 1111
workers: 0
batch_size: 8
num_iter: 5000
valInterval: 250
saved_model: ''
FT: False
optim: 'adam'
lr: 0.001
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
select_data: 'thai_train'
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 30
imgH: 64
imgW: 400
rgb: False
contrast_adjust: 0.0
sensitive: True
PAD: True
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False