number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'กขคงจชซญณดตถทธนบปผฝพฟมยรลวศสหอะัาำิีึืุูเแโใไ็่้'
experiment_name: 'thai_production'
train_data: 'all_data/thai_easyocr_format'
valid_data: 'all_data/thai_easyocr_format/val'
manualSeed: 1111
workers: 4
batch_size: 32
num_iter: 50000
valInterval: 1000
saved_model: ''
FT: False
optim: 'adam'
lr: 0.0005
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
select_data: 'train'
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 50
imgH: 64
imgW: 400
rgb: False
contrast_adjust: 0.1
sensitive: True
PAD: True
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False